### ISSUE TITLE
Filtered Stream

### ISSUE THREAD

**Issue by Roma-Kyrnis** [twitterdev/twitter-api-java-sdk#9]
Can you update StreamingTweet type to add matching_rules variable?
![image](https://user-images.githubusercontent.com/56438694/166314014-504c2fdf-9901-4395-af36-0e2db27e4241.png)

Is [searchStream](https://github.com/twitterdev/twitter-api-java-sdk/blob/main/docs/TweetsApi.md#searchstream) can wait data on stream infinitly? What do you advice me to wait and write stream infinitly?

**Comment by zacmos** [comment]
It looks like a confusion between the api and the response type. 
`searchStream` returns `FilteredStreamingTweet` which contains `matching_rules`. 
`sampleStream` returns `StreamingTweet` that does not have `matching_rules`. 

Regarding the "wait" what issues are you facing? 
Once the streaming API returns the response successfully, you should consume Tweets infinitely. 
If no new Tweet is streamed, a 20-second keep alive heartbeat is being sent, it will look like a new line character.  `reader.readLine()` should take care of it.
 
Your code should handle errors due to the cases mentioned [here](https://developer.twitter.com/en/docs/twitter-api/tweets/filtered-stream/integrate/handling-disconnections)

The Rate Limits issue (in the above link) should be handled by passing `retries` as a first argument. Check [this](https://github.com/twitterdev/twitter-api-java-sdk/blob/main/src/main/java/com/twitter/clientlib/api/TweetsApi.java#:~:text=public%20InputStream%20searchStream(Integer%20retries)

**Comment by Roma-Kyrnis** [comment]
Thank you for detailed instruction and help. Your library is great! I'm writing here to help you to remove errors and others that will use your library, and It's helping me to write a Twitter task and understand Java more deeper.

I'm using `searchStream` while getting this type of error
![image](https://user-images.githubusercontent.com/56438694/166682869-72f12760-b78e-495b-89f3-27492723734e.png)

> Once the streaming API returns the response successfully, you should consume Tweets infinitely.
It's nice. I because get an error `timeout` while pulling tweets. Error appeared like this first I run `searchStream` withiout rules then add certain rules to follow exact users but got `timeout` after 10 seconds the program crush:
![image](https://user-images.githubusercontent.com/56438694/166683222-45e17ca6-52e4-4dbb-8969-7966e25e3ac1.png)

Is it error just an accident? How the `timeout` error can be posible?

**Comment by zacmos** [comment]
Hi Roman, thank you for your help, I really appreciate it.

Regarding your first exception, you are calling `searchStream()` but expecting `StreamingTweet`. 
Please fix it to be `FilteredStreamingTweet`
 e.g.
`Type localVarReturnType = new TypeToken<FilteredStreamingTweet>(){}.getType();`
This should solve the "field `matching_rules` is not defined" issue.

Regarding the timeout.
1. Please make sure that you are using the latest version of `twitter-api-java-sdk`, at the moment `1.2.0`
2. Make sure that your rules are defined before calling `searchStream()`
I hope that this will solve the timeout issue.
The http client's timeout definition is defined here: https://github.com/twitterdev/twitter-api-java-sdk/blob/main/src/main/java/com/twitter/clientlib/ApiClient.java#:~:text=connectTimeout(60%2C%20TimeUnit.SECONDS,readTimeout(60%2C%20TimeUnit.SECONDS)
Getting timeout after 10 seconds makes me think that maybe you should update the dependency version.

**Comment by Roma-Kyrnis** [comment]
Hi Zacmos, Thank you too! I'm glad to have a conversation with you!
Everything you said fixed my errors and gave an explanation for the errors that were previously!

Can you update StreamingTweet to FilteredStreamingTweet in [the docs](https://github.com/twitterdev/twitter-api-java-sdk/blob/main/docs/TweetsApi.md#example-10) for `searchStream`?

**Comment by Roma-Kyrnis** [comment]
Can you update an example to check the null from `fromJson()` func?
It hapens because of empty object from Twitter as I understand, but this object needs to hold the connection.
![image](https://user-images.githubusercontent.com/56438694/166923760-b9e636ab-dacf-4445-ab58-be4a60cf416f.png)
Working example:
``` Java
Object jsonObj = json.getGson().fromJson(line, localVarReturnType);
                    // System.out.println(json.getGson().fromJson(line, localVarReturnType).toString());
                    if (jsonObj == null) {
                        System.out.println("null Object");
                    } else {
                        System.out.println(jsonObj.toString());
                    }
```
![image](https://user-images.githubusercontent.com/56438694/166924219-abeac11e-d707-4e6c-b092-d25ea2aac69e.png)
